# docker-compose.yml
# Cloud-based AI Voice Marketing Agent
# Uses Gemini, Groq, and ElevenLabs APIs (no local models)

services:
  api:
    build: ./backend
    container_name: voice-marketing-agent-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - shared_audio:/app/audio_files
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    mem_limit: 2g
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  dashboard:
    build: ./frontend
    container_name: voice-marketing-agent-frontend
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: voice-marketing-agent-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voicegenie_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d voicegenie_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  shared_audio:
